name: "Deploy Infra Proxmox"

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: CONSTRUÇÃO (Terraform)
  terraform:
    name: "1. Provisioning VMs"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_URL }}
          TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_TOKEN }}
          TF_VAR_vm_user_password: ${{ secrets.VM_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -parallelism=2 -auto-approve

  # JOB 2: CONFIGURAÇÃO (Só roda se o Terraform terminar OK)
  post_install:
    name: "2. K3s and Secrets"
    needs: terraform  # <--- ISSO impede o erro de "No route to host"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check VMs Status
        run: |
          echo "Aguardando as VMs iniciarem o serviço SSH..."
          sleep 30
          ping -c 3 192.168.15.201 || echo "VM Master ainda não responde ping, mas vamos prosseguir."

      # COMENTE AS LINHAS DE KUBECTL POR ENQUANTO
      # Elas só vão funcionar DEPOIS que você rodar o Ansible para instalar o K3s.
      - name: Placeholder for K3s
        run: |
          echo "As VMs foram criadas no Proxmox!"
          echo "Próximo passo: Rodar o Playbook do Ansible para o IP 192.168.15.201"