name: "Deploy Infra Proxmox"

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: TERRAFORM (Cria as VMs no Proxmox)
  terraform:
    name: "1. Provisioning VMs"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_URL }}
          TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_TOKEN }}
          TF_VAR_vm_user_password: ${{ secrets.VM_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -parallelism=2 -auto-approve

  # JOB 2: CONFIGURAÇÃO (Só roda se o Job 1 terminar com sucesso)
  post_install:
    name: "2. Post-Install Config"
    needs: terraform
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Waiting for VMs
        run: |
          echo "Terraform finalizou! Aguardando 30s para as VMs darem boot..."
          sleep 30
          ping -c 3 192.168.15.201 || echo "VM ainda não responde, mas tudo bem."

      # ESTE PASSO ABAIXO FOI DESATIVADO PARA NÃO DAR ERRO
      - name: Create K8s Secret (Disabled)
        run: |
          echo "Pulando criação de secret porque o K3s ainda não foi instalado via Ansible."
          # kubectl create secret generic mysql-pass --from-literal=password='${{ secrets.MYSQL_PASSWORD }}'